### ISSUE TITLE
Would you consider typeshed?

### ISSUE THREAD

**Issue by Avasam** [eggplants/networkx-stubs#3]
Hello!
I am going through stub packages in https://github.com/microsoft/python-type-stubs to remove obsolete ones, upstream some, and move the rest that I can over to https://github.com/python/typeshed .

https://github.com/microsoft/python-type-stubs/tree/main/networkx is bundled with Pylance, and any outdated stubs on there simply hurt Pylance users, so I've been helping move things along. The long-term goals of the maintainers there is to upstream everything to the base repos or typeshed.

Given https://github.com/networkx/networkx/issues/3988 and https://github.com/networkx/networkx/pull/4014, I don't think that `networkx` will ship their own stubs (or inline typing) anytime soon.

Since you've already got some stubs started, I've been wondering if you'd like to migrate them over to typeshed? Some advantages includes a well-developped developper toolkit, lots of testing and type validations, as well as review by Python Typing experts. On top of that, `pyright` comes bundled with types from typeshed and `mypy` automatically recommends installing them.

**Comment by eggplants** [comment]
This repository stubs are not changed after generated with stubgen and not maintained. So you could ignore this repo and shipped the ones in microsoft/python-type-stubs into typeshed.
